version: "3"
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app-container
    ports:
      - 5001:5000
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=mydatabase
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
    networks:
      - my-network

  db:
    image: mysql:latest
    container_name: db-container
    ports:
      - 3307:3306
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
      - MYSQL_ROOT_PASSWORD=rootpassword
    networks:
      - my-network

networks:
  my-network:

volumes:
  mysql-volume:
